// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtf5gDbU_8NbO3pNqzqoyy3-Bo5dXzoBI',
    appId: '1:788580359007:web:0feaadc29d0e4c55caf4ea',
    messagingSenderId: '788580359007',
    projectId: 'instagram-app-5e89c',
    authDomain: 'instagram-app-5e89c.firebaseapp.com',
    storageBucket: 'instagram-app-5e89c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRYj6ibtilS8nbC6M9KUde4dEP29fgWEw',
    appId: '1:788580359007:android:e42ecee6d2891ef7caf4ea',
    messagingSenderId: '788580359007',
    projectId: 'instagram-app-5e89c',
    storageBucket: 'instagram-app-5e89c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5nopHlsF4UoJFTbkODf2_6rjqEXnahw',
    appId: '1:788580359007:ios:54ce6f6a3144e550caf4ea',
    messagingSenderId: '788580359007',
    projectId: 'instagram-app-5e89c',
    storageBucket: 'instagram-app-5e89c.appspot.com',
    iosBundleId: 'com.example.revirpodEcommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5nopHlsF4UoJFTbkODf2_6rjqEXnahw',
    appId: '1:788580359007:ios:54ce6f6a3144e550caf4ea',
    messagingSenderId: '788580359007',
    projectId: 'instagram-app-5e89c',
    storageBucket: 'instagram-app-5e89c.appspot.com',
    iosBundleId: 'com.example.revirpodEcommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtf5gDbU_8NbO3pNqzqoyy3-Bo5dXzoBI',
    appId: '1:788580359007:web:aebe5ae3c57a6ba5caf4ea',
    messagingSenderId: '788580359007',
    projectId: 'instagram-app-5e89c',
    authDomain: 'instagram-app-5e89c.firebaseapp.com',
    storageBucket: 'instagram-app-5e89c.appspot.com',
  );
}
